# Generated by Django 5.1.3 on 2024-12-03 00:33

from django.db import migrations, models
from django.utils.text import slugify

def generate_unique_slug(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    for tag in Tag.objects.all():
        base_slug = slugify(tag.name) or 'tag'
        slug = base_slug
        counter = 1
        while Tag.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        tag.slug = slug
        tag.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(generate_unique_slug, reverse_func),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
