name: Deploy to EC2

on:
  push:
    branches: [ main ]  # 当 main 分支收到推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        HOST: ${{ 43.207.178.32 }}
        USERNAME: ${{ ec2-user }}
      run: |
        # 使用SSH连接到EC2实例，禁用严格的主机密钥检查
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          # 进入项目目录
          cd /home/ec2-user/avocado-blog/AvocadoBlog    
          # 从main分支拉取最新代码
          git pull origin main
          # 激活Python虚拟环境
          source venv/bin/activate
          # 安装/更新项目依赖
          pip install -r requirements.txt
          # 执行数据库迁移
          python manage.py migrate
          # 收集静态文件
          python manage.py collectstatic --noinput
          # 重启Gunicorn服务
          sudo systemctl restart gunicorn
          # 重启Nginx服务
          sudo systemctl restart nginx
        EOF